### PR TITLE
fix: bug where HttpError is returning for deepvalidation

### LINKED ISSUE #488: Bug: unknown_error_validator --- HttpError not found
image

this is occurring to multiple repos,
from a first glance, it could be `milestone` validator, will investigate more

Update: the error stems from deepvalidation component of the milestone validator

### PR DESCRIPTION
**Pull request by shine2lay**
fixes #488

### CODE REVIEW

File: lib/validators/options_processor/deepValidation.js [hunk 1]
```diff
@@ -18,7 +19,24 @@ class DeepValidation {
...
+        // simply skip if the error is 404 (Not Found)
+        if (err.status !== 404) {
+          const errorLog = {
+            log_type: logger.logTypes.ISSUE_GET_FAIL_ERROR,
+            event_id: context.eventId,
+            repo: context.payload.repository.full_name,
+            validator_name: property
+          }
+
+          this.log.info(JSON.stringify(errorLog))
```
Comment (jusx) [inline lib/validators/options_processor/deepValidation.js:35]: Should this be `log.error` since it's an unknown error that can potentially point to a bug.

File: lib/validators/options_processor/deepValidation.js [hunk 2]
```diff
@@ -18,7 +19,24 @@ class DeepValidation {
...
+          throw err
```
Comment (jusx) [inline lib/validators/options_processor/deepValidation.js:36]: I don't think we should throw here since you are already logging the error.

Comment (shine2lay) [reply lib/validators/options_processor/deepValidation.js]: addressed

File: lib/validators/options_processor/deepValidation.js (hunk 1 above)
Comment (shine2lay) [reply lib/validators/options_processor/deepValidation.js]: addressed

**Review by jusx — APPROVED** [review]
